spring:
  application:
    name: demo
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/online_c_compiler
    username: root
    password: 345258
    driver-class-name: com.mysql.cj.jdbc.Driver

file:
  upload-dir: ./data/upload/

mybatis:
  configuration:
    map-underscore-to-camel-case: true

docker:
  images:
    ubuntu: ubuntu-24.04