spring:
  application:
    name: upload-service
  datasource:
    url: jdbc:mysql://localhost:3306/online_c_compiler
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: 30000
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        file-extension: yaml          # 配置文件格式（yaml/properties）
        namespace: public                # 命名空间（可选）
        group: DEFAULT_GROUP          # 配置分组（可选）
      config:
        file-extension: yaml          # 配置文件格式（yaml/properties）
        namespace: public                # 命名空间（可选）
        group: DEFAULT_GROUP          # 配置分组（可选）